apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micro-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: rabbitlokal.com
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: rabbitmq-srv
            port:
              number: {{ .Values.rabbitmq.managementPort }}
  - host: ticketapp.com
    http:
      paths:
      {{- range .Values.microservices }}
      {{- if eq .name "auth" }}
      - path: /api/users/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .name }}-srv
            port:
              number: {{ .port }}
      {{- end }}
      {{- if eq .name "tickets" }}
      - path: /api/tickets/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .name }}-srv
            port:
              number: {{ .port }}
      {{- end }}
      {{- if eq .name "orders" }}
      - path: /api/orders/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .name }}-srv
            port:
              number: {{ .port }}
      {{- end }}
      {{- if eq .name "payments" }}
      - path: /api/payments/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .name }}-srv
            port:
              number: {{ .port }}
      {{- end }}
      {{- if eq .name "client" }}
      - path: /?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .name }}-srv
            port:
              number: {{ .port }}
      {{- end }}
      {{- end }}
