apiVersion: v1
kind: Secret
metadata:
  name: micro-app-secrets
type: Opaque
stringData:
  JWT_KEY: {{ .Values.secrets.jwtKey }}
  MONGO_URI: {{ .Values.secrets.mongoUri }}
  RABBITMQ_URL: {{ .Values.secrets.rabbitmqUrl }}
  STRIPE_KEY: {{ .Values.secrets.stripeKey }}
