apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_KEY: mysecretkey123456789pfe2026
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  rabbitmq_url: amqp://rabbitmq-srv:5672
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
stringData:
  STRIPE_KEY: STRIPE_KEY_PLACEHOLDER
